# Application port.
server:
  port: 8080

# Application name.
spring:
  profiles:
    active: path # See the application-path.yml file.
  application:
    name: gateway
  main:
    # This type is required for Spring API Gateways!
    web-application-type: reactive

logging:
  level:
    org.springframework.web: DEBUG
